name: Rebase on top of QubesOS main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  try-rebase:
    uses: TrenchBoot/.github/.github/workflows/rebase.yml@add-rebase-script
    secrets:
      first-remote-token: ${{secrets.TOKEN}}
    permissions:
      # For creation/deletion/pushing to branches and creating PRs
      contents: write
    with:
      downstream-repo: 'https://github.com/DaniilKl/qubes-antievilmaid.git'
      downstream-branch: 'main'
      upstream-repo: 'https://github.com/QubesOS/qubes-antievilmaid.git'
      upstream-branch: 'main'
      commit-user-name: 'github-actions[bot]'
      commit-user-email: 'github-actions[bot]@users.noreply.github.com'
      cicd-trigger-resume: '7. Rerun the workflow https://github.com/DaniilKl/qubes-antievilmaid/actions/runs/${{ github.run_id }} to resume automated rebase.'
